spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mt_demo
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        multi_tenant: SCHEMA
  flyway:
    enabled: true
    schemas: public
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info
